# File: .github/workflows/template-sync.yml
name: template_sync

on:
    # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # submodules: true
          token: ${{ secrets.KCJ_PAT_TEST }}
          
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.4.0
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.KCJ_PAT_TEST }}
          source_repo_path: dk-teknologisk-kcj/vscode_ros2_ws_template
          upstream_branch: humble # defaults to main
          #pr_labels: <label1>,<label2>[,...] # optional, no default
